INSERT INTO Customers (Customers.First, Last, Email, Birthday, CountryCode, Phone1, Phone2, Phone3, Street, City, State, Zip, Country, Notes)
        VALUES(
               'Nicholas',
               'Petersen',
               'njpetersen@hawkmail.hfcc.edu',
               '1990-01-01',
               '1',
               '123',
               '456',
               '7890',
               '123 Homeward St',
               'Sometown',
               'MI',
                '12345',
               'USA',
               'Owner'),

               (
                'Chad',
                'Banks',
                'crbanks1@hfcc.edu',
                '1990-01-01',
                '1',
                '098',
                '765',
                '4321',
                '098 Somewhere Ln',
                'Citytown',
                'MI',
                '12345',
                'USA',
                'First customer'),

                (
                 'Tom',
                 'Sawyer',
                 'tom@twainsbrain.com',
                 '1785-03-19',
                 '1',
                 '583',
                 '390',
                 '9683',
                 '6839 White Fence Dr',
                 'St. Petersburg',
                 'MO',
                 '56325',
                 'USA',
                 'Doesnt know what digital means. Good customer though.'),

                (
                 'Luke',
                 'Skywalker',
                 'luke@therebellion.com',
                 '1975-09-04',
                 '98',
                 '356',
                 '235',
                 '6933',
                 'Crashed X-wing',
                 'Dagobah',
                 'Sluis Sector',
                 '90000',
                 'Outer Rim',
                 'Highly interested in AI art')

